# specify directories
raw_reads_directory: raw_data
output_directory: preprocessing
read_specification: ['R1', 'R2'] #['1', '2'] # or ['R1', 'R2']
extension: .fastq.gz # or .fastq.gz (should be gzipped regardless) - must include the period!

# specify parameters for TrimGalore -- automatically chcecks the adaptor type
trim_galore:
  quality:  30
  start_trim: 15
  end_trim: 0
  min_read_length: 60

rm_host_reads:
  host_genome: /path/to/bwa/index/ref.fa
  # Mice: /labs/asbhatt/data/host_reference_genomes/mm10/mm10.fa
  # Humans: /labs/asbhatt/data/host_reference_genomes/hg19/hg19.fa
