# specify directories
raw_reads_directory: /path/to/data
output_directory: /path/to/output
read_specification: ['1', '2'] # or ['R1', 'R2']
extension: .fq.gz # or .fastq.gz (should be gzipped regardless) - must include the period!

# specify parameters for TrimGalore -- automatically chcecks the adaptor type
trim_galore:
  quality:  30
  start_trim: 15
  end_trim: 0
  min_read_length: 60

rm_host_reads:
  host_genome: /path/to/bwa/index/ref.fa
