# specify directories
raw_reads_directory: /srv/gsfs0/projects/bhatt/ribado/tools/qc_snakemake/test_sequences
output_directory: /srv/gsfs0/projects/bhatt/ribado/tools/qc_snakemake/test_output
trimgalore_directory: /srv/gsfs0/projects/bhatt/tools/moss_tools/qc/Super-Deduper
# specify parameters for TrimGalore
trim_galore:
  adaptors: illumina
  quality:  30
# specify parameters for SuperDeduper
dereplicate:
  start_trim: 15
  unique_length: 90
# specify parameters for FLASh
interleave:
  min_length: 25
  max_length: 70
  mismatch: 0.1
