# desired output folder for drep
# relative to the directory you'll be running the script
outdir_base: drep

# foler containing the output of DAS_Tool binning
# this must have one folder for each sample, which contains the results from binning
# as well as the combined table of results from all samples (binning_table_all_full.tsv)
das_tool_folder: binning_das_tool

# parameters for selecting bins for drep
# recommended values are 50 and 15
min_completeness: 50
max_contamination: 15

# secondary clustering algorithm for dRep 
# changed from the default of ANImf because of the huge number of files this creates
# see https://drep.readthedocs.io/en/latest/module_descriptions.html#compare
secondary_clustering_algorithm: fastANI