# config for the drep snakefile

# sample_file: same as binning input
sample_file: binning_input.txt

# desired output folder for drep
outdir_base: 'drep'

# foler the das tool binning went into
# this must have one folder for each sample, which contains the results from binning
# as well as the combined table of results from all samples
das_tool_folder: binning_das_tool

# parameters for selecting bins for drep
# recommended values are 50 and 15
min_completeness: 50
max_contamination: 15
